name: Setup Server Blockmango Remake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ngrok
      run: |
        # Download and extract ngrok
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath "C:\ngrok"
        Remove-Item ngrok.zip
        # Configure ngrok using authtoken from secrets
        C:\ngrok\ngrok.exe authtoken "${{ secrets.NGROK_AUTH }}"
    
    - name: Configure RDP
      run: |
        # Set User and Password from GitHub Secrets
        $user = "${{ secrets.ID }}"
        $password = "${{ secrets.PS }}"
        net user $user $password /add
        net localgroup "Remote Desktop Users" $user /add
        net localgroup Administrators $user /add
        # Start RDP service
        Start-Service -Name 'TermService'

    - name: Configure Firewall for RDP
      run: |
        # Allow RDP through Windows Firewall
        New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -Action Allow -LocalPort 3389

    - name: Start ngrok TCP Tunnel
      run: |
        # Start ngrok TCP tunnel for RDP
        Start-Process -NoNewWindow -FilePath "C:\ngrok\ngrok.exe" -ArgumentList "tcp 3389"

    - name: Change CPU Name
      run: |
        # Change the CPU name to 'Hk3u-CPU'
        New-ItemProperty -Path "HKLM:\HARDWARE\DESCRIPTION\System\CentralProcessor\0" -Name "ProcessorNameString" -Value "Hk3u-CPU" -Force

    - name: Configure RAM to 24GB
      run: |
        # Change the maximum memory for the system to 24GB
        bcdedit /set IncreaseUserVa 24576

    - name: Enable RDP Audio
      run: |
        # Enable audio redirection for RDP
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v fDisableAudio /t REG_DWORD /d 0 /f
        # Start the Windows Audio service
        sc config Audiosrv start= auto
        Start-Service Audiosrv

    - name: Keep session alive
      run: |
        # Keep the session alive with periodic checks
        while ($true) {
          Write-Output "RDP session is alive."
          Start-Sleep -Seconds 60
        }
